#! /usr/bin/env bash

export VERIFY_TOKEN='prueba'
export PAGE_ACCESS_TOKEN='EAAFg8AZCng2MBACiaMkyQfY8kwMygwDprx6GlPMsb8wwwBpv1ndiXMNwsB9Lf3ZArEfekClkKm6A5pU5BguKLvVerT0q7kxxAnRgFJcowLZBZAh5UAZA2ihlbZCNFnhocqwwwuzYbUpiheypsOR7iT0Lmbb2ok9IgZAD3dVrxKBXAZDZD'

# Get started message
curl -X POST -H "Content-Type: application/json" -d '{
  "get_started":{
    "payload": "GET_STARTED_PAYLOAD"
  }
}' "https://graph.facebook.com/v2.6/me/messenger_profile?access_token="$PAGE_ACCESS_TOKEN

# Greeting text
curl -X POST -H "Content-Type: application/json" -d '{
  "greeting":[
    {
      "locale":"default",
      "text":"3, 2, 1... MEME IT RIP!"
    }, {
      "locale":"en_US",
      "text":"Help scientists understand today´s world through memes!"
    }
  ]
}' "https://graph.facebook.com/v2.6/me/messenger_profile?access_token="$PAGE_ACCESS_TOKEN

# Run app
python3.6 bot.py
# gunicorn -w 17 \
# 	 -t 17 \
# 	 -b 0.0.0.0:4000 \
# 	 --timeout 30 \
# 	 bot:app
